<?php
  class Constants{
  	
  	
  	
  	const SUCC='00000';
	const USER_NOT_EXIST='20001';
	const ERROR_PASSWORD_INVALID='20002';
	const METHOD_NOT_SUPPORT="10021";
	const APP_KEY_INVALID='10006';
	const SYSTEM_ERROR='10001';
	const EMAIL_INVALID='20003';
	const USERNAME_IS_NULL='20004';
	const PWD_IS_NULL='20005';
	const USERNAME_EXIST='20006';
	const EMAIL_EXIST='20007';
	const SEESION_IS_EXPIRED='20008';
	const THIRD_PART_SOURCE_TYPE_INVALID='20009';
	const OBJECT_NOT_FOUND='20010';
	const PARAM_IS_INVALID='20011';
	const RESULT_IS_NULL='20012';
	const PROGRAM_IS_PUBLISHED='20013';
	const URL_INVALID='20014';
	const PROGRAM_IS_FAVORITY='20015';	
	const PROGRAM_IS_UN_FAVORITY='20016';
	const PERSON_IS_LIKED='20017';
	const NICKNAME_IS_NULL='20018';
	const NICKNAME_IS_EXSTING='20019';
	const KEYWORD_IS_NULL='20020';
	const DUPLICAT_REQUEST='20021';
	const OBJECT_EXIST='20022';
	const NO_RIGHT='20023';	
	const USER_ID_INVALID='20024';
	
	const USER_IS_PRESTIGE_FLAG=1;
	
	const CRSC_TOKEN_KEY="CRSC_TOKEN_KEY";
	
	
	const THIRD_PART_ACCOUNT_SINA='1'; //sina
	const THIRD_PART_ACCOUNT_QQ='2';//QQ
	const THIRD_PART_ACCOUNT_REN_REN='3';//REN REN
	const THIRD_PART_ACCOUNT_DOUBAN='4';// dou ban
	const THIRD_PART_ACCOUNT_LOCAL_CONTACT='5';// local contact
	
	const USER_APPROVAL=1;
	const USER_DELETE=-1;
	
	const DYNAMIC_CONTENT_TYPE_MOVIE=1; // 电影
	const DYNAMIC_CONTENT_TYPE_TV=2;   //        电视剧
	const DYNAMIC_CONTENT_TYPE_SHOW=3;  //综艺节目
	const DYNAMIC_CONTENT_TYPE_COMMENTS=4; //评论
	
	const DYNAMIC_TYPE_WATCH=1;//观看节目
	const DYNAMIC_TYPE_FAVORITY=2; //收藏节目
	const DYNAMIC_TYPE_LIKE=3;//喜欢节目
	const DYNAMIC_TYPE_PUBLISH_PROGRAM=4;//发布节目
	const DYNAMIC_TYPE_SHARE=5;//分享节目
	const DYNAMIC_TYPE_COMMENTS=6;//评论节目 
	const DYNAMIC_TYPE_COMMENT_REPLI=7;//回复评论  
	const DYNAMIC_TYPE_FOLLOW=8;//关注人
	const DYNAMIC_TYPE_UN_FOLLOW=9;//取消关注
	
	const DYNAMIC_TYPE_UN_FAVORITY=10; //取消收藏
	
	const DYNAMIC_CONTENT_STATUS_APPROVAL=1; // 正常
	const DYNAMIC_CONTENT_STATUS_DELETE=2;   //删除
	const DYNAMIC_TYPE_RECOMMEND=12;//推荐节目
	
	const DYNAMIC_TYPE_MAKE_GOOD=13;//顶节目
	
	
	const OBJECT_APPROVAL=1;
	const OBJECT_DELETE=-1;
	
	const NOTIFY_TYPE_FAVORITY=1;//收藏
	const NOTIFY_TYPE_SHARE=2; //分享
	const NOTIFY_TYPE_COMMENT=3; //评论
	const NOTIFY_TYPE_FOLLOW=4;//关注
	const NOTIFY_TYPE_REPLIE_COMMENT=5;//回复评论
	const NOTIFY_TYPE_LIKE_PROGRAM=8;//喜欢节目
	const NOTIFY_TYPE_RECOMMEND_PROGRAM=12;//推荐节目
	const NOTIFY_TYPE_MAKE_GOOD=13;//顶节目
	const NOTIFY_TYPE_LIKE_PERSON=10;//喜欢某人
	const NOTIFY_TYPE_WATCH_PROGRAM=9;//观看节目
	const NOTIFY_TYPE_LIKE_FRIEND=11;//喜欢好友
	
	const NOTIFY_TYPE_UN_FAVORITY=6;//取消收藏
	const NOTIFY_TYPE_UN_FOLLOW=7;//取消关注
	
	const PROGRAM_TYPE_MOVIE=1; //电影
	const PROGRAM_TYPE_TV=2;   //电视剧
	const PROGRAM_TYPE_SHOW=3;  //综艺节目
	const PROGRAM_TYPE_VIDEO=4;  //视频
	const PROGRAM_ANIMATION=131;//动漫
	const SYS_CONF_OPEN_FILTER_KEYWORD="OPEN_FILTER_KEYWORD";
	const SYS_CONF_FILTER_KEYWORD_KEY="FILTER_KEYWORD_KEY";
  }
?>