<?php
  class Constants{
  	const SUCC='00000';
	const USER_NOT_EXIST='20001';
	const ERROR_PASSWORD_INVALID='20002';
	const METHOD_NOT_SUPPORT="10021";
	const APP_KEY_INVALID='10006';
	const SYSTEM_ERROR='10001';
	const EMAIL_INVALID='20003';
	const USERNAME_IS_NULL='20004';
	const PWD_IS_NULL='20005';
	const USERNAME_EXIST='20006';
	const EMAIL_EXIST='20007';
	const SEESION_IS_EXPIRED='20008';
	const THIRD_PART_SOURCE_TYPE_INVALID='20009';
	
	
	
	
	
	
	const THIRD_PART_ACCOUNT_SINA='1'; //sina
	const THIRD_PART_ACCOUNT_QQ='2';//QQ
	const THIRD_PART_ACCOUNT_REN_REN='3';//REN REN
	const THIRD_PART_ACCOUNT_DOUBAN='4';// dou ban
	
	const USER_APPROVAL=1;
	const USER_DELETE=-1;
  }
?>